fail_fast: true
repos:
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v0.9.2
  hooks:
    - id: check-added-large-files
      args: ['--maxkb=500']
    - id: check-byte-order-marker
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: check-symlinks
    - id: debug-statements
    - id: detect-private-key

- repo: local
  hooks:
  - id: prospector
    name: prospector-local
    entry: prospector --messages-only
    language: python
    types: [python]
    exclude: .+/(settings)/.+
    pass_filenames: true

- repo: git://github.com/psf/black
  rev: ''
  hooks:
  - id: black
    args: ["--line-length=120"]
    exclude: .+/(migrations)/.+