output-format: grouped

strictness: high
test-warnings: true
doc-warnings: true

max-line-length: 120


ignore-patterns:
  - __init__.py
  - src

pep257:
  run: false

mccabe:
  run: false

pylint:
  disable:
    - astroid-error
    - abstract-method
    - broad-except
    - cyclic-import
    - invalid-name
    - missing-docstring
    - no-init
    - no-self-use
    - old-style-class
    - redefined-variable-type
    - too-many-ancestors
    - too-many-arguments
    - too-many-instance-attributes
    - too-many-locals
    - unused-argument
  enable:
    - missing-final-newline
  options:
    ignore: migrations
    max-line-length: 120
